### ISSUE TITLE
Script runs, fills fields, does not create account......possible error on last page with payment of none.

### ISSUE THREAD

**Issue by heflin260** [brandonusher/Apple-ID-AppleScript#16]
I am back at this after a couple months away. I have Mavericks 10.9.5 and iTunes 11.3.

I can run the "dry run" and everything seems to work ok as far a filling in the necessary fields. When I go to live run and create the apple ids, the script processes as if it is working normally. It goes through each line of the csv and proceeds to the next account to create. What I noticed was I wasn't getting any emails for verification. After going back and checking, it seems that itunes is not progressing past the screen where you select billing etc. The "none" button is not staying "highlighted" per se. If I step through it manually it gives me an error that says to contact apple.

Has anyone seen this error? I thought about upgrading to iTunes 12, but I didn't know if that would break other things.

**Comment by jafuller** [comment]
This error happens when you reach your Apple appointed limit on the number of ID's from your IP address or your domain.
