### ISSUE TITLE
How to whitelist ip

### ISSUE THREAD

**Issue by saman-php** [brandonusher/Apple-ID-AppleScript#20]
Your script is good but its depend on whitelist ip, because you have one, could you help me to whitelist my ip?

**Comment by brandonusher** [comment]
You'll have to talk to you Apple Rep and they can help you with the process

Sent from my iPhone

On May 25, 2015, at 18:05, Saman A <notifications@github.com> wrote:

Your script is good but its depend on whitelist ip, because you have one,
could you help me to whitelist my ip?

—
Reply to this email directly or view it on GitHub
<https://github.com/brandonusher/Apple-ID-AppleScript/issues/20>.

**Comment by saman-php** [comment]
Tnx for reply, But i want to know whats the process of whitelist an ip before call to apple rep?

**Comment by brandonusher** [comment]
Call Apple Rep for Enterprise with your external IP at the ready.

You can get your IP from google by googling "What's my IP"

Sent from my iPhone

On May 25, 2015, at 18:15, Saman A <notifications@github.com> wrote:

Tnx for reply, But i want to know whats the process of whitelist an ip
before call to apple rep?

—
Reply to this email directly or view it on GitHub
<https://github.com/brandonusher/Apple-ID-AppleScript/issues/20#issuecomment-105347191>
.

**Comment by saman-php** [comment]
I am a web developer, i know this stuff :D, but my situation is complicated, I couldnt find your email address, i will be very appreciated if you send an email to me to ask you some questions.


My mail: saman.php@gmail.com

**Comment by pwldp** [comment]
If your situation is complicated you can try to use TOR network as mentioned by Afif Rais (bottom of page) in https://forgetcomputers.zendesk.com/hc/en-us/articles/201010580-Best-Practices-for-Creating-Apple-IDs

**Comment by saman-php** [comment]
Tnx for helping
I tried every thing like changing IP address after creating one apple id, but the red error will appear all the time, but this if this ways work, its not trusty, because we we give this apple accounts to 500 customers in month, so we have responsibility
