### ISSUE TITLE
Script breaks with iTunes 12.2

### ISSUE THREAD

**Issue by coleman493** [brandonusher/Apple-ID-AppleScript#22]
Issues with iTunes 12.2. 'Store' dropdown tab in iTunes toolbar has been renamed 'Account'.

##On SignOutiTunesAccount()

set storeMenu to menu "Account" of menu bar item "Account" of menu bar 1 of application process "iTunes"
			set storeMenuItems to title of every menu item of storeMenu
		end tell

Issues with executing security question fills as well. Continuing to test.

**Comment by brandonusher** [comment]
Thanks for checking on this. I'll work on getting those patched when you say you are done testing the script

**Comment by jtkant** [comment]
Also when the script gets to the Terms and conditions, it crashes.. It doesn't find the UI-element or something.. You can see the image below..
![img_2209](https://cloud.githubusercontent.com/assets/13161273/8493315/220df058-2161-11e5-8609-63118978a976.JPG)
