### ISSUE TITLE
Enterprise iOS Apple ID Creator.applescript 

### ISSUE THREAD

**Issue by stevejoyce** [brandonusher/Apple-ID-AppleScript#24]
Hi,

I just started using this script to create Apple id's for my school in Winnipeg, MB. The script works great until it gets to enter "Your Date of Birth" I get the following errors.. Unable to fill Month, Unable to fill Day.  All my users account info is enter corectly on the CSV file, but for some reason the script just goes through all the numbers of days and the months and just ends and quit. But the script dose fill in the year with the right information. Is there something I need to enter to make this part work?

Tnanks

**Comment by brandonusher** [comment]
Are you using the Candian Locale? If so, I'll take a look and see what I can do.

Which script are you using? I know I made a Canadian version, but haven't been keeping that up to date.

Also, what OS and iTunes version are you using?

**Comment by stevejoyce** [comment]
Hi Brandonusher,
Are you using the Candian Locale? If so, I'll take a look and see what I can do.
Well I set this setting  on property iTunesCountryCode : "CAN" 

Which script are you using? I know I made a Canadian version, but haven't been keeping that up to date.

I used the main script on your page. I did notice the Canadian was out of date and decided to use the latest script that has been updated.  

Also, what OS and iTunes version are you using?

OS version is 10.10.4 and iTunes 12.2.1.16

Thanks for any help you can give me I am new to this

**Comment by brandonusher** [comment]
One last thing then I'll be able to test tomorrow, what locale are you using inside of iTunes? I assume Canada, but want to make sure before I start testing.

**Comment by stevejoyce** [comment]
Yes, ITunes is set for Canadian store

**Comment by rmiguens** [comment]
Hi Steve,

I believe when I ran across this issue in the past it was due to the order of dates not being correct. What I mean is that the spreadsheet wants Month - Day - Year but the Canadian store wants Day- Month- Year. I may not be 100% correct on the order but I hope you get my drift. I know that I did have to experiment with the spreadsheet before we got it to work. I hope this isn't what is tripping you up so thought I'd chime in to rule it out. 

Thanks
Roy

**Comment by stevejoyce** [comment]
Hi Roy,
Thanks for your feed back! I tried changing the fields in the spreadsheet around yesterday to see if this would fix the problem with no luck. I also compared the Canadian script against the US script and all the coding looks the same. But I am new to apple scripting and might have missed something. I have to take a look again. Thanks

**Comment by stevejoyce** [comment]
Hi brandonusher,

Did you have any luck running testing the script by chance?

**Comment by stevejoyce** [comment]
Hi brandonusher,

Did you have any luck running testing the script by chance

**Comment by brandonusher** [comment]
@stevejoice Sorry, things got out of hand at work. I'll take a look at it on my lunch break today and get back to you

**Comment by brandonusher** [comment]
I got to it a bit early. Try the new version and feel free to reopen this issue if it is not fixed.
