### ISSUE TITLE
Optimal Conditions for Running Script

### ISSUE THREAD

**Issue by thomttran** [brandonusher/Apple-ID-AppleScript#25]
Hi Brandon,

Here's my current environment -
> 10.11 (El Captian), iTunes 12.1.2, iTunes 12.2, iTunes 12.2.1

> 10.9 (Mavericks), iTunes 12.1.2, iTunes 12.2, iTunes 12.2.1

I'm currently setting up a 10.10 (Yosemite) VM, to test the conditions.

The first error I run into deals with the checkbox, under the "Terms and Conditions..." page. Here's the error 

>get value of static text 1 of scroll area 1 of window 1 of application process "iTunes"
	count every UI element of UI element 1 of scroll area 1 of splitter group 1 of window 1 of application process "iTunes"

	get UI element "Terms and Conditions and Apple Privacy Policy" of UI element 1 of scroll area 1 of splitter group 1 of window 1 of application process "iTunes"

	get properties of UI element "Terms and Conditions and Apple Privacy Policy" of UI element 1 of scroll area 1 of splitter group 1 of window "iTunes" of application process "iTunes"

	get checkbox 1 of group 5 of UI element 1 of scroll area 1 of splitter group 1 of window 1 of application process "iTunes"
end tell

>error "System Events got an error: Can’t get text field 1 of group 3 of UI element 1 of scroll area 1 of splitter group 1 of window \"iTunes\" of application process \"iTunes\". Invalid index." number -1719 from text field 1 of group 3 of UI element 1 of scroll area 1 of splitter group 1 of window "iTunes" of application process "iTunes"

These problems are consistent when running under the 10.11 version. What are the recommended environment to run this script?

**Comment by brandonusher** [comment]
As of right now, I only test against 10.10.4 and iTunes 12.2.1 with United States locale in iTunes and USA in the Script.

What locale are you using when you use the script?

**Comment by thomttran** [comment]
I'm currently using the US locale also. 

I didn't see it in the script, but does the locale have to be defined? I only saw POL and CAN.

I will test under the same conditions, as you listed, as soon as I can.

Thanks for your response, Brandon.

**Comment by brandonusher** [comment]
the locale does not need to be set for US, it is the default in the script

**Comment by thomttran** [comment]
Thanks for clearing that up for me. It worked under those specified conditions.

I'll close up the ticket.
