### ISSUE TITLE
AppleScript Error - Can't get UI element

### ISSUE THREAD

**Issue by czych** [brandonusher/Apple-ID-AppleScript#28]
Hey Brandon, 

I came across your script the other day and would love to get this working to deploy 150+ ipads we need to get out as soon as possible. 

I am running the script on OSX 10.8.5 with iTunes 12.1.2 and I am getting stuck with the following error (tried on a newer version of iTunes as well):

AppleScript Error - System Events got an error: Can't get UI element "iBooks" of group 2 of UI element 1 of scroll area 1 of splitter group 1 of window 1 of application process "iTunes."

Any suggestions? iTunes gets taken to the iBooks page and then errors out.

Any help would be appreciated! Thanks!

**Comment by brandonusher** [comment]
Apple keeps changing things so in an effort to support the latest version of iTunes, I only test and update using the latest operating system and itunes versions.

The OS and iTunes versions I have tested it on are OS X 10.10.4 and iTunes 12.2.1

If possible, please try that configuration and let me know. I know iTunes has updated so I am working on checking the script for errors, but until then the script supports iTunes 12.2.1

**Comment by czych** [comment]
Brandon thanks for the fast response, I upgraded to latest OSX 10.10.5 and itunes 12.2.2 and everything is working perfectly. (I did have to add the extra comma in the CSV file as well after "Account Status").

This definitely will make my life easier!
