### ISSUE TITLE
Script requires manual press of "OK" after each user

### ISSUE THREAD

**Issue by selaschuk** [brandonusher/Apple-ID-AppleScript#34]
Currently experiencing an issue where the script requires manual intervention to press an "OK" button at the end of the user creation process. Otherwise it errors out and doesn't proceed to the next user. Not sure if this is just specific to Canadian iTunes or not. Also the province dropdown from the previous screen doesn't clear, but it still creates the user fine.

![itunes](https://cloud.githubusercontent.com/assets/11140912/10734604/b62fd3ce-7bc9-11e5-9f4f-604627714c5f.png)

**Comment by brandonusher** [comment]
Ah... Knew I was forgetting something in the updates, it was the localization. I'll see what I can do, but for now I'm trying to find a solutino to #33

**Comment by brandonusher** [comment]
I believe this was solved a while ago
