### ISSUE TITLE
Error after a while of using the Apple-ID-AppleScript (screenshot)

### ISSUE THREAD

**Issue by tratten76** [brandonusher/Apple-ID-AppleScript#38]
This happens after a while running with the appleid create script.
And it won't go away.. solution i found is to make a new user and start over again and it works.
If i change back to old user itunes will not work.. and i get that error message after a while in the creation process.
I tried deleting safari cache/cookies and also delete pref files under ~/Library/Preferences
it dont help. A new user seems the best solution for me. 
Apple says something is wrong with my internet connection when i have that error.
But i dont hink so.
Anyone else experinced that kind of error message?

![screen shot 2015-12-03 at 07 32 13](https://cloud.githubusercontent.com/assets/16129839/11553561/218d366e-9990-11e5-903b-9e6bcd6caade.png)

**Comment by brandonusher** [comment]
I see this all the time on my computer. I do exactly as you do and create a new user then continue. Nothing is wrong with the Internet connection, Apple just limits certain things I guess that can't be manually fixed. 

There is a clear iTunes cache button under one of the menus but I don't recall where it is right now

**Comment by brandonusher** [comment]
Since I don't have a definitive solution to this, I am closing this issue as it's something Apple seems to be doing (even if they don't admit it)
