### ISSUE TITLE
Selecting "Create apple ID"

### ISSUE THREAD

**Issue by Aliakk** [brandonusher/Apple-ID-AppleScript#41]
hey ev.one:
there is a problem that i catch , when i run this script , itunes goes to get ibook and after click on "Get" btn
new Window "Sign in to ..." shows me in this step script must be click on "Create apple id" but script get an error that say: "System Events got an error: Can’t get scroll area 1 of window 1 of application process "iTunes". Invalid index"

i test it with several version of itunes (12.1.2,,12.2.2) but error dose not change , so where is the problem?!!!!

**Comment by brandonusher** [comment]
@Aliakk What OS version are you running? I last tested this script with OS X 10.11.1

**Comment by d80buckeye** [comment]
I'm running into the same issue on 10.10.4. I've tried iTunes 12.2.2 and 12.3.2.

**Comment by brandonusher** [comment]
More up to date issue is #47
