### ISSUE TITLE
Please answer ! problem with El Capitan

### ISSUE THREAD

**Issue by khazaee** [brandonusher/Apple-ID-AppleScript#42]
Script Error: System Events got an error: Can’t get scroll area 1 of window 1 of application process "iTunes". Invalid index.

**Comment by brandonusher** [comment]
Duplicate of #30 just like your last one. I'm still searching for an answer for this but seeing as it's holiday time, I don't have much time to dedicated to tracking down this issue.

**Comment by khazaee** [comment]
:(

**Comment by seesolve** [comment]
The reference to the element has changed. Use the following line instead.
```
click button "Create New Apple ID"  of window "iTunes" 
```
