### ISSUE TITLE
Terms and conditions

### ISSUE THREAD

**Issue by bugfrisch** [brandonusher/Apple-ID-AppleScript#44]
Hi,

thank you for the script I like it very much.

I have issues here with the "Agree" checkbox of the terms and conditions step (currently I try to dry run).

It prompts me to do this step manually.

This is the error message:
`Unable to locate and check box #2 ''I have read and agree to these terms and conditions.''`

I can manually click on "I have read and agree to these terms and conditions" in iTunes then the script continues. Can you help me on that?

I have MacOS 10.11.2 and iTunes 12.3.2.35

The next problems I have found are following:

1. The birth "day" (month and year work fine). I tried following values 1,10 and 01. Non of them seem to work.
2. The "state" as well as the "postal code" cannot be filled as well.

Can you help me on these issues?

Kind regards
Karol

**Comment by bugfrisch** [comment]
I solved all of the above problems by switching the payment region in iTunes from germany to United States. It would be nice to have support for German Apple IDs. I can help translating if you need support.

**Comment by brandonusher** [comment]
I've been wanting to do something like that @bugfrisch but have yet to get any time to do this.

I will mark this closed and am referencing issue #31
