### ISSUE TITLE
contact Apple

### ISSUE THREAD

**Issue by Jasonface** [brandonusher/Apple-ID-AppleScript#46]
Dose any one contact Itunes Support team to take IP in to whitelisted ??
...........
i think they dont accept this script , because they dont answer me.....
may be im in the wrong way , could someone help me for that????

**Comment by JRHutson** [comment]
iTunes support will not help you with whitelisting. Are you in the US? Are you working with a business or educational institution? You need to determine the right enterprise rep to work with from Apple. They will be able to request that your domain be whitelisted. 

Also, take note of the issue described at the bottom of this thread. https://github.com/brandonusher/Apple-ID-AppleScript/issues/39 I've been meaning to add a note about creating a new user account to the Readme, but haven't gotten to it.

**Comment by brandonusher** [comment]
@JRHutson Is correct, you have to contact Enterprise/Education support to get whitelisted.
